name: Fetch CI Data
run-name: Fetch CI Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:  
    branches:
      - 'main' 
    paths:
      - 'scripts/fetch-ci-nightly-data.js'
      - 'scripts/fetch-ci-pr-data.js'
      - '.github/workflows/fetch-ci-data.yml'



jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dashboard data
        run: |
          # fetch ci nightly data as temporary file
          TOKEN=${{ secrets.GITHUB_TOKEN }} node scripts/fetch-ci-nightly-data.js | tee tmp-data.json
          TOKEN=${{ secrets.GITHUB_TOKEN }} node scripts/fetch-ci-pr-data.js | tee tmp-data2.json

          # switch to a branch specifically for holding latest data
          git config --global user.name "GH Actions Workflow"
          git config --global user.email "<gha@runner>"
          git fetch --all
          git checkout latest-dashboard-data

          # back out whatever data was there
          # git reset HEAD~1

          # overwrite the old data
          mkdir -p data/
          mv tmp-data.json data/job_stats.json
          mv tmp-data2.json data/check_stats.json
          
          # commit
          git add data
          git commit -m '[skip ci] latest ci data'
          git push --force
