name: Fetch CI Nightly Data
run-name: Fetch CI Nightly Data
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dashboard data
        run: |
          # fetch ci nightly data as temporary file
          node scripts/fetch-ci-nightly-data.js | tee tmp-data.json
          # switch to a branch specifically for holding latest data
          git config --global user.name "GH Actions Workflow"
          git config --global user.email "<gha@runner>"
          git fetch --all
          git checkout latest-dashboard-data
          # pull in the latest changes
          git pull
          # overwrite the old data
          git rm -r --cached data/
          rm -rf data/
          mkdir -p data/
          mv tmp-data.json data/job_stats.json
          # commit
          git add data
          git commit -m '[skip ci] latest ci nightly data'
          git push --force
