name: Fetch CI PR Data
run-name: Fetch CI PR Data
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:  
    branches:
      - main 

jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dashboard data
        run: |
          # fetch ci pr data as temporary file
          node scripts/fetch-ci-pr-data.js | tee tmp-data2.json
          # switch to a branch specifically for holding latest data
          git config --global user.name "GH Actions Workflow"
          git config --global user.email "<gha@runner>"
          git fetch --all
          git checkout latest-dashboard-data
          # pull in the latest changes
          git pull
          # overwrite the old data
          git rm -r --cached data/
          rm -rf data/
          mkdir -p data/
          mv tmp-data2.json data/check_stats.json
          # commit
          git add data
          git commit -m '[skip ci] latest ci pr data'
          git push --force
